version: '3'

services:
    web:
       build: './Client'
       ports: 
         - 80:80
    proxy: 
       build: './Proxy'
       volumes: 
         - ./Proxy/db:/usr/src/app/db
       ports:
         - 5050:5050
       environment:
           - ORIENTDB_NAME=${ORIENT_DBNAME}
           - ORIENTDB_PROXY_PASSWORD=${PROXY_USER_PASSWORD}
    orientdb:
       build: './orientdb'
       volumes:
           - ./orientdb/config:/orientdb/config
           - ./orientdb/databases:/orientdb/databases
           - ./orientdb/backup:/orientdb/backup
           - ./orientdb/local:/orientdb/local
       environment:
           - ORIENTDB_NAME=${ORIENT_DBNAME}
           - ORIENTDB_ROOT_PASSWORD=${ORIENT_ROOT_PASSWORD}
           - ORIENTDB_PROXY_PASSWORD=${PROXY_USER_PASSWORD}
       ports:
         - 2424:2424
         - 2480:2480
       entrypoint:
         - /orientdb/entry.sh

